top_pop_artists = [
    "Meghan Trainor",
    "Jonas Brothers",
    "Noah Kahan",
    "Mimi Webb",
    "Katy Perry",
    "Adele",
    "Bruno Mars",
    "Lewis Capaldi",
    "Taylor Swift",
    "Dua Lipa",
    "Olivia Rodrigo",
    "The Weeknd",
    "Doja Cat",
    "Ariana Grande",
    "Billie Eilish",
    "Ed Sheeran",
    "Drake",
    "Harry Styles",
    "Miley Cyrus",
    "Raye",
    "Tate McRae",
    "Troye Sivan",
    "Charli XCX",
    "Sabrina Carpenter",
    "Nicki Minaj",
    "Ice Spice",
    "Rihanna",
    "Selena Gomez",
    "Justin Bieber",
    "Lady Gaga",
    "Sam Smith",
    "Beyoncé",
    "Camila Cabello",
    "Shawn Mendes",
    "Halsey",
    "Zara Larsson",
    "Lana Del Rey",
    "Conan Gray",
    "Charlie Puth",
    "Anne-Marie",
    "Niall Horan",
    "Madison Beer",
    "Ava Max",
    "Lauren Spencer Smith",
    "PinkPantheress",
    "Bebe Rexha",
    "Ellie Goulding",
    "Lauv",
    "Becky Hill",
    "Tove Lo"
]