top_pop_artists = [
    "Taylor Swift",
    "Dua Lipa",
    "Olivia Rodrigo",
    "The Weeknd",
    "Doja Cat",
    "Ariana Grande",
    "Billie Eilish",
    "Ed Sheeran",
    "Drake",
    "Harry Styles",
    "Miley Cyrus",
    "Raye",
    "Tate McRae",
    "Troye Sivan",
    "Charli XCX",
    "Sabrina Carpenter",
    "Kali Uchis",
    "Nicki Minaj",
    "Ice Spice",
    "Bad Bunny",
    "Rihanna",
    "Selena Gomez",
    "Justin Bieber",
    "Lady Gaga",
    "Sam Smith",
    "Beyoncé",
    "Camila Cabello",
    "Shawn Mendes",
    "Halsey",
    "Zara Larsson",
    "Lana Del Rey",
    "Conan Gray",
    "Charlie Puth",
    "Marshmello",
    "Anne-Marie",
    "Niall Horan",
    "Madison Beer",
    "Ava Max",
    "Lauren Spencer Smith",
    "PinkPantheress",
    "Bebe Rexha",
    "Ellie Goulding",
    "Måneskin",
    "BLACKPINK",
    "Jung Kook",
    "Lauv",
    "Becky Hill",
    "Rina Sawayama",
    "Tove Lo"
]